<?php
return array (
  'alert_opt_out.conversation_message_reaction' => 'Reacts to your message in a conversation',
  'alert_opt_out.dbtech_ecommerce_download_insert' => 'Updates a watched product',
  'alert_opt_out.dbtech_ecommerce_download_reaction' => 'Reacts to an update to your product',
  'alert_opt_out.dbtech_ecommerce_license_expired' => 'Your license expired',
  'alert_opt_out.dbtech_ecommerce_license_expiring' => 'Your license is about to expire',
  'alert_opt_out.dbtech_ecommerce_order_shipped' => 'Ships an order you placed',
  'alert_opt_out.dbtech_ecommerce_product_insert' => 'Creates a product in a watched category',
  'alert_opt_out.dbtech_ecommerce_product_mention' => 'Mentions you in a product',
  'alert_opt_out.dbtech_ecommerce_product_reaction' => 'Reacts to your product',
  'alert_opt_out.dbtech_ecommerce_rating_reply' => 'Replies to your product review',
  'alert_opt_out.dbtech_ecommerce_rating_review' => 'Reviews your product',
  'alert_opt_out.post_forumwatch_insert' => 'Posts in a watched forum',
  'alert_opt_out.post_insert' => 'Replies to a watched thread',
  'alert_opt_out.post_mention' => 'Mentions you in a message',
  'alert_opt_out.post_quote' => 'Quotes your message',
  'alert_opt_out.post_reaction' => 'Reacts to your message',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Also comments on a profile post',
  'alert_opt_out.profile_post_comment_reaction' => 'Reacts to your profile post comment',
  'alert_opt_out.profile_post_comment_your_post' => 'Comments on your profile posts for other members',
  'alert_opt_out.profile_post_comment_your_profile' => 'Comments on your profile or status',
  'alert_opt_out.profile_post_insert' => 'Posts on your profile',
  'alert_opt_out.profile_post_mention' => 'Mentions you in a profile post or comment',
  'alert_opt_out.profile_post_reaction' => 'Reacts to your profile post',
  'alert_opt_out.trophy_award' => 'Awards you a new trophy',
  'alert_opt_out.user_following' => 'Starts following you',
);